server {
    listen 80;
    listen [::]:80;
    server_name _;
    absolute_redirect off;

    root /usr/share/nginx/blog;
    index index.html;

    location = / {
        try_files /index.html @post_list;
    }

    location @post_list {
        return 302 /post.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
